import "./App.css";
import { UploadForm } from "./Components/Form";
import { QrCodeImage, QrCodeScanner } from "./Components/QrCode";

import React, { useState } from "react";

function App() {
  const [fileId, setFileId] = useState("");

  return (
    <div className="App">
      <UploadForm setFileId={setFileId} />
      {fileId && <QrCodeImage fileId={fileId} />}
      <QrCodeScanner />
    </div>
  );
}

// Questions:
// 1. What is the unique ID for each image? Is this ID generated by the mongodb (unique of each upload) or hashed from the image file (unique of each file)?

export default App;
